### PR TITLE
Fix for Norwegian Bokmål translation

### PR DESCRIPTION
**Pull request by sandakersmann**
Minor corrections to the Norwegian Bokmål translation

### CODE REVIEW

**Comment by sandakersmann** [comment]
@Cybnate Please merge :)

**Comment by Cybnate** [comment]
Matthew can merge this with next release. Thanks for updates.
Thinking of getting it to one of the translations services so it is easier to contribute

**Comment by sandakersmann** [comment]
Ok :)

**Comment by MatthewLM** [comment]
These changes have been included in the code. I think they got included when updating the app in line with the peercoin app.

Thanks.

**Pull request closed without merging**
